# Generated by Django 3.1.2 on 2020-10-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Buchung', 'verbose_name_plural': 'Buchungen'},
        ),
        migrations.AddField(
            model_name='event',
            name='manager_mail',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-Mail'),
        ),
    ]
